Docs - Updated Submit your exercise section
form3tech-oss/interview-accountapi pull request #60
Opened 2021-12-23 05:15 UTC by adithyaakrishna

Signed-off-by: Adithya Krishna <aadithya794@gmail.com>

Description:
This PR Fixes #56

2022-01-16 13:28 UTC, adithyaakrishna commented
@ewilde @liamg Could you please review this PR? Thanks in advance :)

2022-01-16 13:30 UTC, liamg commented
@adithyaakrishna I'm afraid I no longer work for FORM3 so can't merge this.

2022-02-02 09:45 UTC, ewilde-form3 requested changes
@adithyaakrishna thank you for your PR. I've made a small suggestion which links to the users profile. The @ syntax is in the correct syntax, hopefully this makes it clearer

2022-02-02 09:45 UTC, ewilde-form3 commented on README.md
> +- [Invite](https://help.github.com/en/articles/inviting-collaborators-to-a-personal-repository) **_form3tech-interviewer-1_** to your private repo
```suggestion
- [Invite](https://help.github.com/en/articles/inviting-collaborators-to-a-personal-repository) [@form3tech-interviewer-1](https://github.com/form3tech-interviewer-1) to your private repo
```

2022-05-25 08:45 UTC, ewilde-form3 approved these changes

2022-05-25 08:45 UTC, merged